steps:
  - name: gcr.io/cloud-builders/docker
  - args: ['build', '-t', 'gcr.io/cloud-run-test-405515/github.com/widifaizakhmad/notes-app-backend']
  - name: gcr.io/cloud-builders/docker
  - args: ['push', 'gcr.io/cloud-run-test-405515/github.com/widifaizakhmad/notes-app-backend']
options:
  logging: CLOUD_LOGGING_ONLY
