steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'notes-app-backend'  
      - '--image=asia-southeast2-docker.pkg.dev/cloud-run-test-405515/cloud-run-source-deploy/notes-app-backend:latest'  
options:
  logging: CLOUD_LOGGING_ONLY
