steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - 'run'
      - 'deploy'
      - 'notes-app-backend'  # Replace with your service name
      - '--image=gcr.io/cloud-run-test-405515/notes-app-backend:latest'  # Replace 'your-project-id' with your GCP project ID
      - '--platform=managed'
      - '--region=us-central1'  # Replace with your desired region
      - '--allow-unauthenticated' # Remove or adjust this flag based on your authentication needs
options:
  logging: CLOUD_LOGGING_ONLY
